TAP version 13
    # Subtest: /interpreted/test/close-bad/runner.js
        # Subtest: close interperted tester
        not ok 1 - Error: fake error
          ---
          at:
            line: 12
            column: 14
            file: runner.js
            function: Object.interpreted.close
          stack: |
            Object.interpreted.close (runner.js:12:14)
            /interpreted/interpreted.js:97:20
            _combinedTickCallback (internal/process/next_tick.js:67:7)
            process._tickCallback (internal/process/next_tick.js:98:9)
          test: close interperted tester
          message: 'Error: fake error'
          source: |
            callback(new Error('fake error'));
          ...
        1..1
        # failed 1 of 1 tests
    not ok 1 - close interperted tester # time=16.96ms
      ---
      at:
        line: 95
        column: 7
        file: /interpreted/interpreted.js
        type: Intrepreted
        function: Intrepreted._assignClose
        method: _assignClose
      results:
        plan:
          start: 1
          end: 1
        count: 1
        pass: 0
        ok: false
        fail: 1
        time: 16.96
      source: |
        tap.test('close interperted tester', this.tapOptions, function (t) {
      ...

    1..1
    # failed 1 of 1 tests
    # time=50.639ms
not ok 1 - /interpreted/test/close-bad/runner.js # time=216.507ms
  ---
  timeout: 30000
  file: /interpreted/test/close-bad/runner.js
  results:
    ok: false
    count: 1
    pass: 0
    fail: 1
    plan:
      start: 1
      end: 1
  exitCode: 1
  command: /node
  arguments:
    - /interpreted/test/close-bad/runner.js
  ...

1..1
# failed 1 of 1 tests
# time=235.693ms
